name: Run Lunch Menu Script

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install beautifulsoup4 requests

    - name: Run the script
      run: python main.py

    - name: Commit and push the changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add menu/menu.json
        git commit -m "Update menu.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
